# languages.py
import os
import sys

# --- BU FONKSİYON EN ÜSTTE OLMALI ---
def resource_path(relative_path):
    """ Dosyanın nerede olduğunu akıllıca bulur """
    # 1. Önce PyInstaller'ın içindeki (_internal) klasöre bak
    if hasattr(sys, '_MEIPASS'):
        path_in_meipass = os.path.join(sys._MEIPASS, relative_path)
        if os.path.exists(path_in_meipass):
            return path_in_meipass

    # 2. Orada yoksa EXE'nin yanındaki klasöre bak
    try:
        base_path = os.path.dirname(sys.executable)
    except:
        base_path = os.path.abspath(".")
    
    path_next_to_exe = os.path.join(base_path, relative_path)
    if os.path.exists(path_next_to_exe):
        return path_next_to_exe
        
    # 3. Hiçbiri değilse geliştirme ortamıdır
    return os.path.join(os.path.abspath("."), relative_path)

LANGUAGES = {
    "EN": {
        "name": "ENGLISH",
        "font": resource_path("assets/fonts/Alagard.ttf"),
        "size_offset": 0,
        "direction": "LTR",
        "HYPE_WORDS": ["AMAZING!", "LEGEND!", "INSANE!", "GODLIKE!", "PERFECT!"],
        "text": {
            "PLAY": "PLAY",
            "SETTINGS": "SETTINGS",
            "COLLECTION": "COLLECTION",
            "TRAINING": "TRAINING",
            "EXIT": "EXIT",
            "LAYER": "LAYER",
            "QUOTA": "QUOTA",
            "TRIBUTE": "TRIBUTE",
            "JUDGMENT": "JUDGMENT",
            "LABOR": "LABOR",
            "FAVOR": "FAVOR",
            "TOTAL": "TOTAL",
            "MENU": "MENU",
            "SHIFT_SCORE": "SHIFT SCORE",
            "DEMO_TITLE": "DEMO COMPLETED",
            "DEMO_MSG": "You have survived 8 Layers... for now.\nThe Pharaoh's debt is not fully paid.",
            "ENTER_ETERNITY": "ENTER ETERNITY",
            "FREEDOM_1": "Freedom is just another prison.",
            "FREEDOM_2": "The debt is paid. The blocks remain.",
            "PHARAOH_1": "Work harder.",
            "PHARAOH_2": "The stone waits.",
            "PAUSE_MSG": "Return to Main Menu?",
            "YES": "YES",
            "NO": "NO",
            "PAYMENT": "PAYMENT",
            "TOTAL_DEBT": "TOTAL DEBT",
            "CONTINUE": "CONTINUE",
            "COLOR_MATCH": "COLOR MATCH!",
            "RUNE_CHIPS": "RUNE CHIPS!",
            "GAMBLE_WIN": "GAMBLE WIN!",
            "REROLL": "REROLL!",
            "RUNE_APPLIED": "RUNE APPLIED!",
            "ARCH_BONUS": "Architect Bonus",
            "DEMO_HINT_MSG": "Pay the debt to reveal the true ending.",
            "RESET_BTN": "RESET DATA",
            "BTN_TRY_AGAIN": "TRY AGAIN",
            "LBL_PYRO_BOSS": "PYRO BOSS",
            "PYRO_DEFEATED": "PYRO MODE DEFEATED",
            "YOU_DIED": "YOU DIED",
            "RESET_CONFIRM_TITLE": "WIPE SAVE?",
            "RESET_CONFIRM_MSG": "This will erase all progress.\nAre you sure?",
            "TUT_STEP0_TITLE": "WELCOME TO SPHENKS",
            "TUT_STEP0_MSG": "Welcome, Architect.\nThe Pharaoh demands a perfect grid.\nDrag blocks to the board to begin.",
            "TUT_STEP1_TITLE": "MASTER CONTROLS",
            "TUT_STEP1_MSG": "Precision is key.\nPress 'R' to ROTATE blocks.\nPress 'E' to FLIP blocks.",
            "TUT_STEP2_TITLE": "PURIFY THE HAND",
            "TUT_STEP2_MSG": "Some blocks are flawed.\nDrag a block to the RED TRASH ICON\nto discard it for a small cost.",
            "TUT_STEP3_TITLE": "SCORING & STRATEGY",
            "TUT_STEP3_MSG": "Fill rows completely to score.\nCombos multiply your Labor and Favor.\nReach the Quota to survive.",
            "TUT_STEP4_TITLE": "MEET YOUR ARSENAL",
            "TUT_STEP4_MSG": "You are not alone.\nRunes and Items will appear here.\nThey are tools of the gods.",
            "TUT_STEP5_TITLE": "USE YOUR RUNE",
            "TUT_STEP5_MSG": "A Rune has appeared!\nDrag the RUNE onto a block in your hand\nto enchant it with power.",
            "TUT_STEP6_TITLE": "YOU'RE READY!",
            "TUT_STEP6_MSG": "The basics are done.\nNow, survive the infinite layers.\nThe Pharaoh is watching.",
            "BEST_RUN": "BEST RUN",
            "ITEMS": {
                "sniper": {"name": "SNIPER", "desc": "Edge matches give x2 Mult."},
                "miner": {"name": "MINER", "desc": "+$1 for every Stone block cleared."},
                "architect": {"name": "ARCHITECT", "desc": "+50 Score for placing without clear."},
                "void_walker": {"name": "VOID WALKER", "desc": "x3 Mult if Void Count is less than 5."},
                "midas": {"name": "KING MIDAS", "desc": "+$0.5 for every single block cleared."},
                "recycler": {"name": "RECYCLER", "desc": "Discarding blocks becomes FREE."},
                "blood_pact": {"name": "BLOOD PACT", "desc": "x4 Mult, but -1 Void Capacity."},
                "savings_bond": {"name": "SAVINGS BOND", "desc": "Earn +20% Interest on round end."},
                "golden_ticket": {"name": "GOLD TICKET", "desc": "Earn +$3 when placing a GOLD block."},
                "gamblers_dice": {"name": "GAMBLER'S DICE", "desc": "25% chance to destroy block & get x5 Score."},
                "ruby_lens": {"name": "RUBY LENS", "desc": "+2 Mult for every RED block scored."},
                "sapphire_lens": {"name": "SAPPHIRE LENS", "desc": "+2 Mult for every BLUE block scored."},
                "dark_matter": {"name": "DARK MATTER", "desc": "Gain a massive x10 Mult."},
                "infinity_stone": {"name": "INFINITY STONE", "desc": "+$5 and x2 Mult on every clear."},
                "chronos": {"name": "CHRONOS", "desc": "Gain +50% Interest on round end."},
                "rune_fire": {"name": "FIRE RUNE", "desc": "Destroys blocks in a 3x3 area."},
                "rune_ice": {"name": "ICE RUNE", "desc": "Freezes a block. Gravity won't affect it."},
                "rune_void": {"name": "VOID RUNE", "desc": "Destroys all blocks of the same color."},
                "rune_wind": {"name": "WIND RUNE", "desc": "Shifts a row horizontally."},
                "rune_earth": {"name": "EARTH RUNE", "desc": "Turns a block into solid stone."},
                "refresh_shop": {"name": "REROLL", "desc": "Refresh all items in the bazaar."},
                "unknown": {"name": "UNKNOWN", "desc": "A mysterious artifact."}
            },
            "BAZAAR": "BAZAAR",
            "TOTEMS": "TOTEMS",
            "RUNES": "RUNES",
            "NEXT_ROUND": "NEXT ROUND >",
            "LBL_ROTATE": "ROTATE",
            "LBL_FLIP": "FLIP",
            "BTN_COMING_SOON": "COMING SOON",
            "COMING_SOON_TITLE": "COMING SOON v1.0",
            "CS_PYRO": "New Pyro Mode 🔥",
            "CS_LANGS": "Russian & Arabic Support 🌍",
            "CS_STORY": "Full Story: 4 Worlds 📜",
            "CS_VISUALS": "New VFX & Backgrounds ✨",
            "CS_MORE": "And much more! 🚀",
            "BACK": "BACK"
        }
    },
    "TR": {
        "name": "TURKCE",
        "font": resource_path("assets/fonts/Alagard.ttf"),
        "size_offset": 0,
        "direction": "LTR",
        "HYPE_WORDS": ["EFSANE!", "HARIKA!", "INANILMAZ!", "SOV YAPTIN!", "MUKEMMEL!"],
        "text": {
            "PLAY": "OYNA",
            "SETTINGS": "AYARLAR",
            "COLLECTION": "KOLEKSIYON",
            "TRAINING": "EGITIM",
            "EXIT": "CIKIS",
            "LAYER": "KATMAN",
            "QUOTA": "KOTA",
            "TRIBUTE": "HARAC",
            "JUDGMENT": "YARGI",
            "LABOR": "EMEK",
            "FAVOR": "LUTUF",
            "TOTAL": "TOPLAM",
            "MENU": "MENU",
            "SHIFT_SCORE": "VARDIYA SKORU",
            "DEMO_TITLE": "DEMO TAMAMLANDI",
            "DEMO_MSG": "8 Katmani hayatta kalarak bitirdin...\nFiravun'a olan borcun henuz bitmedi.",
            "ENTER_ETERNITY": "SONSUZLUK MODU",
            "FREEDOM_1": "Ozgurluk baska bir hapishanedir.",
            "FREEDOM_2": "Borc bitti. Bloklar bitmedi.",
            "PHARAOH_1": "Daha siki calis.",
            "PHARAOH_2": "Taslar seni bekler.",
            "PAUSE_MSG": "Ana Menuye Don?",
            "YES": "EVET",
            "NO": "HAYIR",
            "PAYMENT": "ODEME",
            "TOTAL_DEBT": "KALAN BORC",
            "CONTINUE": "DEVAM ET",
            "COLOR_MATCH": "RENK UYUMU!",
            "RUNE_CHIPS": "RUN PARCALARI!",
            "GAMBLE_WIN": "KUMAR KAZANDI!",
            "REROLL": "YENILE!",
            "RUNE_APPLIED": "RUN BASILDI!",
            "ARCH_BONUS": "Mimar Bonusu",
            "DEMO_HINT_MSG": "Gercek sonu gormek icin borcu kapat.",
            "RESET_BTN": "SIFIRLA",
            "BTN_TRY_AGAIN": "TEKRAR DENE",
            "LBL_PYRO_BOSS": "PYRO PATRON",
            "PYRO_DEFEATED": "PYRO MODU YILANDI",
            "YOU_DIED": "OLDUN",
            "RESET_CONFIRM_TITLE": "VERIYI SIL?",
            "RESET_CONFIRM_MSG": "Tum ilerleme silinecek.\nEmin misin?",
            "TUT_STEP0_TITLE": "SPHENKS'E HOSGELDIN",
            "TUT_STEP0_MSG": "Hosgeldin Mimar.\nFiravun kusursuz bir yapi ister.\nBaslamak icin blogu izgaraya surukle.",
            "TUT_STEP1_TITLE": "KONTROL USTALIGI",
            "TUT_STEP1_MSG": "Hassasiyet onemlidir.\n'R' ile DONDUR.\n'E' ile TERS CEVIR.",
            "TUT_STEP2_TITLE": "ELI ARINDIR",
            "TUT_STEP2_MSG": "Bazi bloklar kusurludur.\nOnlari yok etmek icin KIRMIZI COP KUTUSUNA\nsurukle. Bunun bir bedeli vardir.",
            "TUT_STEP3_TITLE": "SKOR VE STRATEJI",
            "TUT_STEP3_MSG": "Satirlari doldurarak puan kazan.\nKombolar Emek ve Lutuf puanini katlar.\nHayatta kalmak icin Kotaya ulas.",
            "TUT_STEP4_TITLE": "CEPHANELIK",
            "TUT_STEP4_MSG": "Yalniz degilsin.\nRunler ve Esyalar burada belirir.\nOnlar tanrilarin araclaridir.",
            "TUT_STEP5_TITLE": "RUNU KULLAN",
            "TUT_STEP5_MSG": "Bir Run belirdi!\nRunu elindeki bir blogun uzerine surukle\nve onu gucle donat.",
            "TUT_STEP6_TITLE": "HAZIRSIN!",
            "TUT_STEP6_MSG": "Temelleri ogrendin.\nSimdi sonsuz katmanlarda hayatta kal.\nFiravun seni izliyor.",
            "BEST_RUN": "EN IYI SKOR",
            "ITEMS": {
                "sniper": {"name": "KESKIN NISANCI", "desc": "Kenar eslesmeleri x2 Carpan verir."},
                "miner": {"name": "MADENCI", "desc": "Kirilan her Tas icin +$1 kazan."},
                "architect": {"name": "MIMAR", "desc": "Patlatmadan koyarsan +50 Puan."},
                "void_walker": {"name": "HICLIK GEZGINI", "desc": "Hiclik < 5 ise x3 Carpan kazan."},
                "midas": {"name": "KRAL MIDAS", "desc": "Kirilan her blok icin +$0.5 kazan."},
                "recycler": {"name": "GERI DONUSUMCU", "desc": "Bloklari cope atmak BEDAVA."},
                "blood_pact": {"name": "KAN ANLASMASI", "desc": "x4 Carpan, ama -1 Hiclik Kapasitesi."},
                "savings_bond": {"name": "TASARRUF BONOSU", "desc": "Tur sonunda +%20 Faiz kazan."},
                "golden_ticket": {"name": "ALTIN BILET", "desc": "ALTIN blok koyarsan +$3 kazan."},
                "gamblers_dice": {"name": "KUMARBAZ ZARI", "desc": "%25 sansla blogu yok edip x5 Puan verir."},
                "ruby_lens": {"name": "YAKUT MERCEK", "desc": "Her KIRMIZI blok icin +2 Carpan."},
                "sapphire_lens": {"name": "SAFIR MERCEK", "desc": "Her MAVI blok icin +2 Carpan."},
                "dark_matter": {"name": "KARANLIK MADDE", "desc": "Devasa x10 Carpan kazan."},
                "infinity_stone": {"name": "SONSUZLUK TASI", "desc": "Her temizlemede +$5 ve x2 Carpan."},
                "chronos": {"name": "KRONOS", "desc": "Tur sonunda +%50 Faiz kazan."},
                "rune_fire": {"name": "ATES RUNU", "desc": "3x3 alanindaki bloklari yok eder."},
                "rune_ice": {"name": "BUZ RUNU", "desc": "Blogu dondurur. Yercekimi etkilemez."},
                "rune_void": {"name": "HICLIK RUNU", "desc": "Ayni renkteki tum bloklari siler."},
                "rune_wind": {"name": "RUZGAR RUNU", "desc": "Bir satiri yatay olarak kaydirir."},
                "rune_earth": {"name": "TOPRAK RUNU", "desc": "Blogu kirilmaz tasa cevirir."},
                "refresh_shop": {"name": "YENILE", "desc": "Pazardaki esyalari yeniler."},
                "unknown": {"name": "BILINMEYEN", "desc": "Gizemli bir nesne."}
            },
            "BAZAAR": "PAZAR",
            "TOTEMS": "TOTEMLER",
            "RUNES": "RUNLER",
            "NEXT_ROUND": "SONRAKI TUR >",
            "LBL_ROTATE": "DONDUR",
            "LBL_FLIP": "CEVIR",
            "BTN_COMING_SOON": "PEK YAKINDA",
            "COMING_SOON_TITLE": "TAM SÜRÜMDE GELECEKLER",
            "CS_PYRO": "Yeni Pyro Modu 🔥",
            "CS_LANGS": "Rusça ve Arapça Desteği 🌍",
            "CS_STORY": "Tam Hikaye: 4 Farklı Dünya 📜",
            "CS_VISUALS": "Gelişmiş Efektler ve Arkaplanlar ✨",
            "CS_MORE": "Ve çok daha fazlası! 🚀",
            "BACK": "GERI"
        }
    },
    "DE": {
        "name": "DEUTSCH",
        "font": resource_path("assets/fonts/Alagard.ttf"),
        "size_offset": 0,
        "direction": "LTR",
        "HYPE_WORDS": ["WUNDERBAR!", "LEGENDE!", "WAHNSINN!", "PERFEKT!", "MEISTER!"],
        "text": {
            "PLAY": "SPIELEN",
            "SETTINGS": "EINSTELLUNG",
            "COLLECTION": "SAMMLUNG",
            "TRAINING": "TRAINING",
            "EXIT": "BEENDEN",
            "LAYER": "EBENE",
            "QUOTA": "QUOTE",
            "TRIBUTE": "TRIBUT",
            "JUDGMENT": "URTEIL",
            "LABOR": "ARBEIT",
            "FAVOR": "GUNST",
            "TOTAL": "GESAMT",
            "MENU": "MENU",
            "SHIFT_SCORE": "SCHICHT PUNKTE",
            "DEMO_TITLE": "DEMO BEENDET",
            "DEMO_MSG": "Du hast 8 Ebenen überlebt... für jetzt.\nDie Schuld des Pharaos ist noch nicht beglichen.",
            "ENTER_ETERNITY": "EWIGKEIT",
            "FREEDOM_1": "Freiheit ist nur ein weiteres Gefängnis.",
            "FREEDOM_2": "Schuld beglichen. Blöcke bleiben.",
            "PHARAOH_1": "Arbeite härter.",
            "PHARAOH_2": "Der Stein wartet.",
            "PAUSE_MSG": "Zurück zum Menü?",
            "YES": "JA",
            "NO": "NEIN",
            "PAYMENT": "ZAHLUNG",
            "TOTAL_DEBT": "RESTSCHULD",
            "CONTINUE": "WEITER",
            "COLOR_MATCH": "FARB-COMBO!",
            "RUNE_CHIPS": "RUNEN SPLITTER!",
            "GAMBLE_WIN": "GEWINN!",
            "REROLL": "NEU WÜRFELN!",
            "RUNE_APPLIED": "RUNE BENUTZT!",
            "ARCH_BONUS": "Architekten Bonus",
            "DEMO_HINT_MSG": "Bezahle die Schuld für das wahre Ende.",
            "RESET_BTN": "ZURÜCKSETZEN",
            "BTN_TRY_AGAIN": "ERNEUT VERSUCHEN",
            "LBL_PYRO_BOSS": "PYRO BOSS",
            "PYRO_DEFEATED": "PYRO MODUS BESIEGT",
            "YOU_DIED": "DU BIST TOT",
            "RESET_CONFIRM_TITLE": "LÖSCHEN?",
            "RESET_CONFIRM_MSG": "Alle Fortschritte werden gelöscht.\nBist du sicher?",
            # --- TUTORIAL (DE) ---
            "TUT_STEP0_TITLE": "WILLKOMMEN BEI SPHENKS",
            "TUT_STEP0_MSG": "Willkommen, Architekt.\nDer Pharao verlangt ein perfektes Raster.\nZiehe Blöcke auf das Brett, um zu beginnen.",
            "TUT_STEP1_TITLE": "STEUERUNG MEISTERN",
            "TUT_STEP1_MSG": "Präzision ist der Schlüssel.\nDrücke 'R' zum DREHEN.\nDrücke 'E' zum WENDEN.",
            "TUT_STEP2_TITLE": "HAND REINIGEN",
            "TUT_STEP2_MSG": "Manche Blöcke sind fehlerhaft.\nZiehe sie in den ROTEN MÜLLEIMER,\num sie gegen eine Gebühr zu entsorgen.",
            "TUT_STEP3_TITLE": "PUNKTE & STRATEGIE",
            "TUT_STEP3_MSG": "Fülle Reihen komplett für Punkte.\nKombos vervielfachen Arbeit und Gunst.\nErreiche die Quote zum Überleben.",
            "TUT_STEP4_TITLE": "DEIN ARSENAL",
            "TUT_STEP4_MSG": "Du bist nicht allein.\nRunen und Items erscheinen hier.\nSie sind Werkzeuge der Götter.",
            "TUT_STEP5_TITLE": "BENUTZE DEINE RUNE",
            "TUT_STEP5_MSG": "Eine Rune ist erschienen!\nZiehe die RUNE auf einen Block in deiner Hand,\num ihn mit Macht zu verzaubern.",
            "TUT_STEP6_TITLE": "DU BIST BEREIT!",
            "TUT_STEP6_MSG": "Die Grundlagen sind gelegt.\nÜberlebe nun die unendlichen Ebenen.\nDer Pharao beobachtet dich.",
            "BEST_RUN": "BESTE SERIE",
            "ITEMS": {
                "sniper": {"name": "SCHARFSCHÜTZE", "desc": "Kantenübereinstimmungen geben x2 Mult."},
                "miner": {"name": "BERGMANN", "desc": "+$1 für jeden abgebauten Steinblock."},
                "architect": {"name": "ARCHITEKT", "desc": "+50 Punkte ohne Clears platziert."},
                "void_walker": {"name": "VOID WALKER", "desc": "x3 Mult wenn Void < 5."},
                "midas": {"name": "KÖNIG MIDAS", "desc": "+$0.5 für jeden abgebauten Block."},
                "recycler": {"name": "RECYCLER", "desc": "Blöcke wegwerfen wird KOSTENLOS."},
                "blood_pact": {"name": "BLUTPAKT", "desc": "x4 Mult, aber -1 Void-Kapazität."},
                "savings_bond": {"name": "SPARANLEIHE", "desc": "Erhalte +20% Zinsen am Rundenende."},
                "golden_ticket": {"name": "GOLDTICKET", "desc": "Erhalte +$3 beim Platzieren eines Goldblocks."},
                "gamblers_dice": {"name": "WÜRFEL DES GLÜCKSSPIELERS", "desc": "25% Chance, Block zu zerstören & x5 Punkte."},
                "ruby_lens": {"name": "RUBINLINSE", "desc": "+2 Mult für jeden roten Block."},
                "sapphire_lens": {"name": "SAPHIRLINSE", "desc": "+2 Mult für jeden blauen Block."},
                "dark_matter": {"name": "DUNKLE MATERIE", "desc": "Erhalte massiven x10 Mult."},
                "infinity_stone": {"name": "STEIN DER UNENDLICHKEIT", "desc": "+$5 und x2 Mult bei jedem Clear."},
                "chronos": {"name": "CHRONOS", "desc": "Erhalte +50% Zinsen am Rundenende."},
                "rune_fire": {"name": "FEUERRUNE", "desc": "Zerstört Blöcke in 3x3 Bereich."},
                "rune_ice": {"name": "EISRUNE", "desc": "Friert einen Block ein."},
                "rune_void": {"name": "VOIDRUNE", "desc": "Zerstört alle Blöcke derselben Farbe."},
                "rune_wind": {"name": "WINDRUNE", "desc": "Verschiebt eine Reihe horizontal."},
                "rune_earth": {"name": "ERDRUNE", "desc": "Verwandelt einen Block in Stein."},
                "refresh_shop": {"name": "ERNEUERUNG", "desc": "Aktualisiere alle Marktartikel."},
                "unknown": {"name": "UNBEKANNT", "desc": "Ein rätselhaftes Artefakt."}
            },
            "BAZAAR": "BASAR",
            "TOTEMS": "TOTEMS",
            "RUNES": "RUNEN",
            "NEXT_ROUND": "NÄCHSTE RUNDE >",
            "LBL_ROTATE": "DREHEN",
            "LBL_FLIP": "WENDEN",
            "BTN_COMING_SOON": "DEMNÄCHST",
            "COMING_SOON_TITLE": "DEMNÄCHST v1.0",
            "CS_PYRO": "Neuer Pyro-Modus 🔥",
            "CS_LANGS": "Russisch & Arabisch Support 🌍",
            "CS_STORY": "Volle Story: 4 Welten 📜",
            "CS_VISUALS": "Neue VFX & Hintergründe ✨",
            "CS_MORE": "Und vieles mehr! 🚀",
            "BACK": "ZURÜCK"
        }
    },
    "ES": {
        "name": "ESPANOL",
        "font": resource_path("assets/fonts/Alagard.ttf"),
        "size_offset": 0,
        "direction": "LTR",
        "HYPE_WORDS": ["INCREIBLE!", "LEYENDA!", "LOCO!", "PERFECTO!", "MAESTRO!"],
        "text": {
            "PLAY": "JUGAR",
            "SETTINGS": "AJUSTES",
            "COLLECTION": "COLECCION",
            "TRAINING": "ENTRENAR",
            "EXIT": "SALIR",
            "LAYER": "CAPA",
            "QUOTA": "CUOTA",
            "TRIBUTE": "TRIBUTO",
            "JUDGMENT": "JUICIO",
            "LABOR": "LABOR",
            "FAVOR": "FAVOR",
            "TOTAL": "TOTAL",
            "MENU": "MENU",
            "SHIFT_SCORE": "PUNTOS TURNO",
            "DEMO_TITLE": "DEMO COMPLETADA",
            "DEMO_MSG": "Has sobrevivido 8 Capas... por ahora.\nLa deuda del Faraón no está pagada.",
            "ENTER_ETERNITY": "ETERNIDAD",
            "FREEDOM_1": "La libertad es otra prisión.",
            "FREEDOM_2": "Deuda pagada. Los bloques quedan.",
            "PHARAOH_1": "Trabaja más.",
            "PHARAOH_2": "La piedra espera.",
            "PAUSE_MSG": "Volver al Menú?",
            "YES": "SI",
            "NO": "NO",
            "PAYMENT": "PAGO",
            "TOTAL_DEBT": "DEUDA TOTAL",
            "CONTINUE": "CONTINUAR",
            "COLOR_MATCH": "COLOR COMBO!",
            "RUNE_CHIPS": "FICHAS RUNA!",
            "GAMBLE_WIN": "GANASTE!",
            "REROLL": "RE-TIRAR!",
            "RUNE_APPLIED": "RUNA APLICADA!",
            "ARCH_BONUS": "Bono Arquitecto",
            "DEMO_HINT_MSG": "Paga la deuda para ver el final real.",
            "RESET_BTN": "REINICIAR",
            "BTN_TRY_AGAIN": "INTENTAR DE NUEVO",
            "LBL_PYRO_BOSS": "JEFE PYRO",
            "PYRO_DEFEATED": "MODO PYRO DERROTADO",
            "YOU_DIED": "MORISTE",
            "RESET_CONFIRM_TITLE": "¿BORRAR DATOS?",
            "RESET_CONFIRM_MSG": "Se borrará todo el progreso.\n¿Estás seguro?",
            # --- TUTORIAL (ES) ---
            "TUT_STEP0_TITLE": "BIENVENIDO A SPHENKS",
            "TUT_STEP0_MSG": "Bienvenido, Arquitecto.\nEl Faraón exige una cuadrícula perfecta.\nArrastra bloques al tablero para comenzar.",
            "TUT_STEP1_TITLE": "CONTROLES MAESTROS",
            "TUT_STEP1_MSG": "La precisión es clave.\nPresiona 'R' para ROTAR.\nPresiona 'E' para VOLTEAR.",
            "TUT_STEP2_TITLE": "PURIFICA LA MANO",
            "TUT_STEP2_MSG": "Algunos bloques son defectuosos.\nArrastra al BASURERO ROJO\npara descartar por un costo.",
            "TUT_STEP3_TITLE": "PUNTUACIÓN Y ESTRATEGIA",
            "TUT_STEP3_MSG": "Llena filas para ganar puntos.\nLos combos multiplican Labor y Favor.\nAlcanza la Cuota para sobrevivir.",
            "TUT_STEP4_TITLE": "TU ARSENAL",
            "TUT_STEP4_MSG": "No estás solo.\nRunas y Objetos aparecerán aquí.\nSon herramientas de los dioses.",
            "TUT_STEP5_TITLE": "USA TU RUNA",
            "TUT_STEP5_MSG": "¡Apareció una Runa!\nArrastra la RUNA a un bloque en tu mano\npara encantarlo con poder.",
            "TUT_STEP6_TITLE": "¡ESTÁS LISTO!",
            "TUT_STEP6_MSG": "Lo básico está hecho.\nAhora sobrevive a las capas infinitas.\nEl Faraón te observa.",
            "BEST_RUN": "MEJOR RACHA",
            "ITEMS": {
                "sniper": {"name": "FRANCOTIRADOR", "desc": "Coincidencias de borde dan x2 Mult."},
                "miner": {"name": "MINERO", "desc": "+$1 por cada bloque de piedra."},
                "architect": {"name": "ARQUITECTO", "desc": "+50 Puntos sin despejar."},
                "void_walker": {"name": "CAMINANTE VACÍO", "desc": "x3 Mult si Vacío < 5."},
                "midas": {"name": "REY MIDAS", "desc": "+$0.5 por cada bloque despejado."},
                "recycler": {"name": "RECICLADOR", "desc": "Descartar bloques es GRATIS."},
                "blood_pact": {"name": "PACTO DE SANGRE", "desc": "x4 Mult, pero -1 Capacidad Vacío."},
                "savings_bond": {"name": "BONO DE AHORRO", "desc": "Gana +20% Interés al final."},
                "golden_ticket": {"name": "BOLETO DE ORO", "desc": "Gana +$3 al colocar oro."},
                "gamblers_dice": {"name": "DADOS DE JUGADOR", "desc": "25% de destruir y ganar x5."},
                "ruby_lens": {"name": "LENTE DE RUBÍ", "desc": "+2 Mult por cada rojo."},
                "sapphire_lens": {"name": "LENTE DE ZAFIRO", "desc": "+2 Mult por cada azul."},
                "dark_matter": {"name": "MATERIA OSCURA", "desc": "Gana masivo x10 Mult."},
                "infinity_stone": {"name": "PIEDRA DEL INFINITO", "desc": "+$5 y x2 Mult al despejar."},
                "chronos": {"name": "CHRONOS", "desc": "Gana +50% Interés al final."},
                "rune_fire": {"name": "RUNA DE FUEGO", "desc": "Destruye en área 3x3."},
                "rune_ice": {"name": "RUNA DE HIELO", "desc": "Congela un bloque."},
                "rune_void": {"name": "RUNA DE VACÍO", "desc": "Destruye mismo color."},
                "rune_wind": {"name": "RUNA DE VIENTO", "desc": "Desplaza fila horizontal."},
                "rune_earth": {"name": "RUNA DE TIERRA", "desc": "Convierte en piedra."},
                "refresh_shop": {"name": "RENOVAR", "desc": "Actualiza bazaar."},
                "unknown": {"name": "DESCONOCIDO", "desc": "Artefacto misterioso."}
            },
            "BAZAAR": "MERCADO",
            "TOTEMS": "TOTEMS",
            "RUNES": "RUNAS",
            "NEXT_ROUND": "SIGUIENTE >",
            "LBL_ROTATE": "ROTAR",
            "LBL_FLIP": "VOLTEAR",
            "BTN_COMING_SOON": "PRÓXIMAMENTE",
            "COMING_SOON_TITLE": "PRÓXIMAMENTE v1.0",
            "CS_PYRO": "Nuevo Modo Pyro 🔥",
            "CS_LANGS": "Soporte Ruso y Árabe 🌍",
            "CS_STORY": "Historia Completa: 4 Mundos 📜",
            "CS_VISUALS": "Nuevos VFX y Fondos ✨",
            "CS_MORE": "¡Y mucho más! 🚀",
            "BACK": "ATRÁS"
        }
    },
    "ZH": {
        "name": "CHINESE",
        "font": resource_path("assets/fonts/Zpix.ttf"),
        "size_offset": 2,
        "direction": "LTR",
        "HYPE_WORDS": ["太棒了!", "传说!", "疯狂!", "超神!", "完美!"],
        "text": {
            "PLAY": "开始游戏",
            "SETTINGS": "设置",
            "COLLECTION": "收藏",
            "TRAINING": "教程",
            "EXIT": "退出",
            "LAYER": "层",
            "QUOTA": "配额",
            "TRIBUTE": "贡品",
            "JUDGMENT": "审判",
            "LABOR": "劳力",
            "FAVOR": "恩赐",
            "TOTAL": "总分",
            "MENU": "菜单",
            "SHIFT_SCORE": "班次得分",
            "DEMO_TITLE": "演示结束",
            "DEMO_MSG": "你幸存了8层... 暂时。\n法老的债务尚未还清。",
            "ENTER_ETERNITY": "进入永恒",
            "FREEDOM_1": "自由只是另一种牢笼。",
            "FREEDOM_2": "债务已清。方块仍在。",
            "PHARAOH_1": "更努力工作。",
            "PHARAOH_2": "石头在等待。",
            "PAUSE_MSG": "返回主菜单？",
            "YES": "是",
            "NO": "否",
            "PAYMENT": "支付",
            "TOTAL_DEBT": "总债务",
            "CONTINUE": "继续",
            "COLOR_MATCH": "颜色匹配!",
            "RUNE_CHIPS": "符文碎片!",
            "GAMBLE_WIN": "赌博获胜!",
            "REROLL": "重掷!",
            "RUNE_APPLIED": "符文已应用!",
            "ARCH_BONUS": "建筑师奖励",
            "DEMO_HINT_MSG": "偿还债务以揭示真正的结局。",
            "RESET_BTN": "重置数据",
            "BTN_TRY_AGAIN": "再试一次",
            "LBL_PYRO_BOSS": "火焰之王",
            "PYRO_DEFEATED": "火焰模式已被击败",
            "YOU_DIED": "你死了",
            "RESET_CONFIRM_TITLE": "删除存档？",
            "RESET_CONFIRM_MSG": "所有进度将被删除。\n你确定吗？",
            # --- TUTORIAL (ZH) ---
            "TUT_STEP0_TITLE": "欢迎来到 SPHENKS",
            "TUT_STEP0_MSG": "欢迎你，建筑师。\n法老要求完美的网格。\n将方块拖到棋盘上开始。",
            "TUT_STEP1_TITLE": "掌握控制",
            "TUT_STEP1_MSG": "精准是关键。\n按 'R' 旋转方块。\n按 'E' 翻转方块。",
            "TUT_STEP2_TITLE": "净化手牌",
            "TUT_STEP2_MSG": "有些方块有缺陷。\n拖到红色垃圾桶\n花费金币丢弃它们。",
            "TUT_STEP3_TITLE": "得分与策略",
            "TUT_STEP3_MSG": "填满行以得分。\n连击倍增劳力和恩赐。\n达到配额以生存。",
            "TUT_STEP4_TITLE": "你的军火库",
            "TUT_STEP4_MSG": "你并不孤单。\n符文和道具会出现在这里。\n它们是神的工具。",
            "TUT_STEP5_TITLE": "使用符文",
            "TUT_STEP5_MSG": "符文出现了！\n将符文拖到手牌中的方块上\n赋予它力量。",
            "TUT_STEP6_TITLE": "准备好了！",
            "TUT_STEP6_MSG": "基础已完成。\n现在在无限层中生存。\n法老在注视着你。",
            "BEST_RUN": "最佳记录",
            "ITEMS": {
                "sniper": {"name": "狙击手", "desc": "边缘匹配给予 x2 倍数。"},
                "miner": {"name": "矿工", "desc": "每清除一个石块 +$1。"},
                "architect": {"name": "建筑师", "desc": "放置无清除 +50 分数。"},
                "void_walker": {"name": "虚空行者", "desc": "虚空 < 5 时 x3 倍数。"},
                "midas": {"name": "金王", "desc": "每清除一个块 +$0.5。"},
                "recycler": {"name": "回收者", "desc": "丢弃块变为免费。"},
                "blood_pact": {"name": "血誓", "desc": "x4 倍数，-1 虚空容量。"},
                "savings_bond": {"name": "储蓄债券", "desc": "回合结束 +20% 利息。"},
                "golden_ticket": {"name": "金票", "desc": "放置金块 +$3。"},
                "gamblers_dice": {"name": "赌徒骰子", "desc": "25% 销毁块获 x5 分。"},
                "ruby_lens": {"name": "红宝石镜头", "desc": "每个红块 +2 倍数。"},
                "sapphire_lens": {"name": "蓝宝石镜头", "desc": "每个蓝块 +2 倍数。"},
                "dark_matter": {"name": "暗物质", "desc": "获得巨大 x10 倍数。"},
                "infinity_stone": {"name": "无限宝石", "desc": "清除时 +$5 和 x2 倍数。"},
                "chronos": {"name": "时间之神", "desc": "回合结束 +50% 利息。"},
                "rune_fire": {"name": "火符文", "desc": "销毁 3x3 区域。"},
                "rune_ice": {"name": "冰符文", "desc": "冻结一个块。"},
                "rune_void": {"name": "虚空符文", "desc": "销毁同色块。"},
                "rune_wind": {"name": "风符文", "desc": "水平移动行。"},
                "rune_earth": {"name": "土符文", "desc": "变为石块。"},
                "refresh_shop": {"name": "刷新", "desc": "刷新市集。"},
                "unknown": {"name": "未知", "desc": "神秘的神器。"}
            },
            "BAZAAR": "集市",
            "TOTEMS": "图腾",
            "RUNES": "符文",
            "NEXT_ROUND": "下一轮 >",
            "LBL_ROTATE": "旋转",
            "LBL_FLIP": "翻转",
            "BTN_COMING_SOON": "即将推出",
            "COMING_SOON_TITLE": "即将推出 v1.0",
            "CS_PYRO": "新火焰模式 🔥",
            "CS_LANGS": "俄语和阿拉伯语支持 🌍",
            "CS_STORY": "完整故事：4个世界 📜",
            "CS_VISUALS": "新视觉特效和背景 ✨",
            "CS_MORE": "还有更多！🚀",
            "BACK": "返回"
        }
    },
    "PT": {
        "name": "PORTUGUES",
        "font": resource_path("assets/fonts/Alagard.ttf"),
        "size_offset": 0,
        "direction": "LTR",
        "HYPE_WORDS": ["INCRIVEL!", "LENDA!", "INSANO!", "DIVINO!", "PERFEITO!"],
        "text": {
            "PLAY": "JOGAR",
            "SETTINGS": "CONFIGURACAO",
            "COLLECTION": "COLECAO",
            "TRAINING": "TREINO",
            "EXIT": "SAIR",
            "LAYER": "CAMADA",
            "QUOTA": "META",
            "TRIBUTE": "TRIBUTO",
            "JUDGMENT": "JULGAMENTO",
            "LABOR": "TRABALHO",
            "FAVOR": "FAVOR",
            "TOTAL": "TOTAL",
            "MENU": "MENU",
            "SHIFT_SCORE": "PONTOS TURNO",
            "DEMO_TITLE": "DEMO CONCLUIDA",
            "DEMO_MSG": "Voce sobreviveu 8 Camadas... por enquanto.\nA divida do Farao nao foi paga.",
            "ENTER_ETERNITY": "ETERNIDADE",
            "FREEDOM_1": "Liberdade e outra prisao.",
            "FREEDOM_2": "Divida paga. Os blocos ficam.",
            "PHARAOH_1": "Trabalhe mais.",
            "PHARAOH_2": "A pedra espera.",
            "PAUSE_MSG": "Voltar ao Menu?",
            "YES": "SIM",
            "NO": "NAO",
            "PAYMENT": "PAGAMENTO",
            "TOTAL_DEBT": "DIVIDA TOTAL",
            "CONTINUE": "CONTINUAR",
            "COLOR_MATCH": "COR COMBINADA!",
            "RUNE_CHIPS": "FRAGMENTOS!",
            "GAMBLE_WIN": "VITORIA!",
            "REROLL": "ROLAR!",
            "RUNE_APPLIED": "RUNA APLICADA!",
            "ARCH_BONUS": "Bonus Arquiteto",
            "DEMO_HINT_MSG": "Pague a dívida para ver o final real.",
            "RESET_BTN": "RESETAR",
            "BTN_TRY_AGAIN": "TENTAR NOVAMENTE",
            "LBL_PYRO_BOSS": "CHEFE PYRO",
            "PYRO_DEFEATED": "MODO PYRO DERROTADO",
            "YOU_DIED": "VOCÊ MORREU",
            "RESET_CONFIRM_TITLE": "APAGAR DADOS?",
            "RESET_CONFIRM_MSG": "Todo o progresso será apagado.\nTem certeza?",
            # --- TUTORIAL (PT) ---
            "TUT_STEP0_TITLE": "BEM-VINDO AO SPHENKS",
            "TUT_STEP0_MSG": "Bem-vindo, Arquiteto.\nO Faraó exige uma grade perfeita.\nArraste blocos para o tabuleiro para começar.",
            "TUT_STEP1_TITLE": "CONTROLES MESTRES",
            "TUT_STEP1_MSG": "Precisão é a chave.\nPressione 'R' para GIRAR.\nPressione 'E' para VIRAR.",
            "TUT_STEP2_TITLE": "PURIFIQUE A MÃO",
            "TUT_STEP2_MSG": "Alguns blocos são falhos.\nArraste para a LIXEIRA VERMELHA\npara descartar por um custo.",
            "TUT_STEP3_TITLE": "PONTUAÇÃO E ESTRATÉGIA",
            "TUT_STEP3_MSG": "Preencha linhas para pontuar.\nCombos multiplicam Trabalho e Favor.\nAtinga a Meta para sobreviver.",
            "TUT_STEP4_TITLE": "SEU ARSENAL",
            "TUT_STEP4_MSG": "Você não está sozinho.\nRunas e Itens aparecerão aqui.\nSão ferramentas dos deuses.",
            "TUT_STEP5_TITLE": "USE SUA RUNA",
            "TUT_STEP5_MSG": "Uma Runa apareceu!\nArraste a RUNA para um bloco na sua mão\npara encantá-lo com poder.",
            "TUT_STEP6_TITLE": "VOCÊ ESTÁ PRONTO!",
            "TUT_STEP6_MSG": "O básico está feito.\nAgora sobreviva às camadas infinitas.\nO Faraó está observando.",
            "BEST_RUN": "Melhor Desempenho",
            "ITEMS": {
                "sniper": {"name": "Atirador", "desc": "Correspondências nas bordas dão x2 multiplicador."},
                "miner": {"name": "Mineiro", "desc": "+$1 para cada bloco de pedra removido."},
                "architect": {"name": "Arquiteto", "desc": "Colocações sem remoção +50 pontos."},
                "void_walker": {"name": "Caminhante do Vazio", "desc": "x3 multiplicador quando vazio < 5."},
                "midas": {"name": "Midas", "desc": "+$0,50 para cada bloco removido."},
                "recycler": {"name": "Reciclador", "desc": "Blocos descartados se tornam gratuitos."},
                "blood_pact": {"name": "Pacto de Sangue", "desc": "x4 multiplicador, -1 capacidade de vazio."},
                "savings_bond": {"name": "Título de Poupança", "desc": "+20% de juros no final do turno."},
                "golden_ticket": {"name": "Bilhete Dourado", "desc": "+$3 para cada bloco dourado colocado."},
                "gamblers_dice": {"name": "Dados do Apostador", "desc": "25% chance de destruir bloco para x5 pontos."},
                "ruby_lens": {"name": "Lente de Rubi", "desc": "+2 multiplicador por cada bloco vermelho."},
                "sapphire_lens": {"name": "Lente de Safira", "desc": "+2 multiplicador por cada bloco azul."},
                "dark_matter": {"name": "Matéria Escura", "desc": "Obtenha um x10 multiplicador enorme."},
                "infinity_stone": {"name": "Pedra do Infinito", "desc": "+$5 e x2 multiplicador ao remover."},
                "chronos": {"name": "Chronos", "desc": "+50% de juros no final do turno."},
                "rune_fire": {"name": "Runa de Fogo", "desc": "Destrói área 3x3."},
                "rune_ice": {"name": "Runa de Gelo", "desc": "Congela um bloco."},
                "rune_void": {"name": "Runa do Vazio", "desc": "Destrói blocos da mesma cor."},
                "rune_wind": {"name": "Runa do Vento", "desc": "Move linha horizontalmente."},
                "rune_earth": {"name": "Runa da Terra", "desc": "Transforma em bloco de pedra."},
                "refresh_shop": {"name": "Atualizar", "desc": "Atualiza a loja."},
                "unknown": {"name": "Desconhecido", "desc": "Artefato misterioso."}
            },
            "BAZAAR": "Mercado",
            "TOTEMS": "Totens",
            "RUNES": "Runas",
            "NEXT_ROUND": "Próximo >",
            "LBL_ROTATE": "GIRAR",
            "LBL_FLIP": "VIRAR",
            "BTN_COMING_SOON": "EM BREVE",
            "COMING_SOON_TITLE": "EM BREVE v1.0",
            "CS_PYRO": "Novo Modo Pyro 🔥",
            "CS_LANGS": "Suporte Russo e Árabe 🌍",
            "CS_STORY": "História Completa: 4 Mundos 📜",
            "CS_VISUALS": "Novos VFX e Fundos ✨",
            "CS_MORE": "E muito mais! 🚀",
            "BACK": "VOLTAR"
        }
    },
    "FR": {
        "name": "FRANCAIS",
        "font": resource_path("assets/fonts/Alagard.ttf"),
        "size_offset": 0,
        "direction": "LTR",
        "HYPE_WORDS": ["INCROYABLE!", "LEGENDE!", "DEMENT!", "DIVIN!", "PARFAIT!"],
        "text": {
            "PLAY": "JOUER",
            "SETTINGS": "PARAMETRES",
            "COLLECTION": "COLLECTION",
            "TRAINING": "TUTORIEL",
            "EXIT": "QUITTER",
            "LAYER": "COUCHE",
            "QUOTA": "QUOTA",
            "TRIBUTE": "TRIBUT",
            "JUDGMENT": "JUGEMENT",
            "LABOR": "LABEUR",
            "FAVOR": "FAVEUR",
            "TOTAL": "TOTAL",
            "MENU": "MENU",
            "SHIFT_SCORE": "SCORE TOUR",
            "DEMO_TITLE": "DEMO TERMINEE",
            "DEMO_MSG": "Vous avez survécu à 8 couches... pour l'instant.\nLa dette du Pharaon n'est pas payée.",
            "ENTER_ETERNITY": "ETERNITE",
            "FREEDOM_1": "La liberte est une autre prison.",
            "FREEDOM_2": "Dette payee. Les blocs restent.",
            "PHARAOH_1": "Travaillez plus dur.",
            "PHARAOH_2": "La pierre attend.",
            "PAUSE_MSG": "Retour au Menu?",
            "YES": "OUI",
            "NO": "NON",
            "PAYMENT": "PAIEMENT",
            "TOTAL_DEBT": "DETTE TOTALE",
            "CONTINUE": "CONTINUER",
            "COLOR_MATCH": "COULEURS!",
            "RUNE_CHIPS": "FRAGMENTS!",
            "GAMBLE_WIN": "VICTOIRE!",
            "REROLL": "RELANCER!",
            "RUNE_APPLIED": "RUNE APPLIQUEE!",
            "ARCH_BONUS": "Bonus Architecte",
            "DEMO_HINT_MSG": "Payez la dette pour la vraie fin.",
            "RESET_BTN": "RÉINITIALISER",
            "BTN_TRY_AGAIN": "RÉESSAYER",
            "LBL_PYRO_BOSS": "BOSS PYRO",
            "PYRO_DEFEATED": "MODE PYRO VAINCU",
            "YOU_DIED": "VOUS ÊTES MORT",
            "RESET_CONFIRM_TITLE": "EFFACER ?",
            "RESET_CONFIRM_MSG": "Tout progrès sera effacé.\nÊtes-vous sûr ?",
            # --- TUTORIAL (FR) ---
            "TUT_STEP0_TITLE": "BIENVENUE À SPHENKS",
            "TUT_STEP0_MSG": "Bienvenue, Architecte.\nLe Pharaon exige une grille parfaite.\nGlissez des blocs sur le plateau pour commencer.",
            "TUT_STEP1_TITLE": "MAÎTRISEZ LES COMMANDES",
            "TUT_STEP1_MSG": "La précision est la clé.\nAppuyez sur 'R' pour PIVOTER.\nAppuyez sur 'E' pour RETOURNER.",
            "TUT_STEP2_TITLE": "PURIFIEZ LA MAIN",
            "TUT_STEP2_MSG": "Certains blocs sont imparfaits.\nGlissez vers la POUBELLE ROUGE\npour jeter contre un coût.",
            "TUT_STEP3_TITLE": "SCORE ET STRATÉGIE",
            "TUT_STEP3_MSG": "Remplissez les lignes pour marquer.\nLes combos multiplient Labeur et Faveur.\nAtteignez le Quota pour survivre.",
            "TUT_STEP4_TITLE": "VOTRE ARSENAL",
            "TUT_STEP4_MSG": "Vous n'êtes pas seul.\nRunes et Objets apparaîtront ici.\nCe sont des outils des dieux.",
            "TUT_STEP5_TITLE": "UTILISEZ VOTRE RUNE",
            "TUT_STEP5_MSG": "Une Rune est apparue !\nGlissez la RUNE sur un bloc en main\npour l'enchanter.",
            "TUT_STEP6_TITLE": "VOUS ÊTES PRÊT !",
            "TUT_STEP6_MSG": "Les bases sont acquises.\nSurvivez aux couches infinies.\nLe Pharaon vous observe.",
            "BEST_RUN": "Meilleure Performance",
            "ITEMS": {
                "sniper": {"name": "Tireur", "desc": "Les correspondances des bords donnent x2 multiplicateur."},
                "miner": {"name": "Mineur", "desc": "+$1 pour chaque bloc de pierre retiré."},
                "architect": {"name": "Architecte", "desc": "Placements sans retrait +50 points."},
                "void_walker": {"name": "Marcheur du Vide", "desc": "x3 multiplicateur quand vide < 5."},
                "midas": {"name": "Midas", "desc": "+$0,50 pour chaque bloc retiré."},
                "recycler": {"name": "Recycleur", "desc": "Les blocs jetés deviennent gratuits."},
                "blood_pact": {"name": "Pacte de Sang", "desc": "x4 multiplicateur, -1 capacité vide."},
                "savings_bond": {"name": "Obligation d'épargne", "desc": "+20% d'intérêt en fin de tour."},
                "golden_ticket": {"name": "Ticket d'Or", "desc": "+$3 pour chaque bloc d'or placé."},
                "gamblers_dice": {"name": "Dés du Joueur", "desc": "25% détruire bloc pour x5 points."},
                "ruby_lens": {"name": "Lentille de Rubis", "desc": "+2 multiplicateur par bloc rouge."},
                "sapphire_lens": {"name": "Lentille de Saphir", "desc": "+2 multiplicateur par bloc bleu."},
                "dark_matter": {"name": "Matière Noire", "desc": "Obtenez un énorme x10 multiplicateur."},
                "infinity_stone": {"name": "Pierre de l'Infini", "desc": "+$5 et x2 multiplicateur au retrait."},
                "chronos": {"name": "Chronos", "desc": "+50% d'intérêt en fin de tour."},
                "rune_fire": {"name": "Rune de Feu", "desc": "Détruit la zone 3x3."},
                "rune_ice": {"name": "Rune de Glace", "desc": "Gèle un bloc."},
                "rune_void": {"name": "Rune du Vide", "desc": "Détruit même couleur."},
                "rune_wind": {"name": "Rune du Vent", "desc": "Déplace ligne horizontal."},
                "rune_earth": {"name": "Rune de Terre", "desc": "Convertir en bloc pierre."},
                "refresh_shop": {"name": "Actualiser", "desc": "Actualise le bazar."},
                "unknown": {"name": "Inconnu", "desc": "Artefact mystérieux."}
            },
            "BAZAAR": "Bazaar",
            "TOTEMS": "Totems",
            "RUNES": "Runes",
            "NEXT_ROUND": "Prochaine >",
            "LBL_ROTATE": "TOURNER",
            "LBL_FLIP": "RETOURNER",
            "BTN_COMING_SOON": "BIENTÔT",
            "COMING_SOON_TITLE": "BIENTÔT v1.0",
            "CS_PYRO": "Nouveau Mode Pyro 🔥",
            "CS_LANGS": "Support Russe et Arabe 🌍",
            "CS_STORY": "Histoire Complète: 4 Mondes 📜",
            "CS_VISUALS": "Nouveaux VFX et Arrière-plans ✨",
            "CS_MORE": "Et bien plus ! 🚀",
            "BACK": "RETOUR"
        }
    },
    "IT": {
        "name": "ITALIANO",
        "font": resource_path("assets/fonts/Alagard.ttf"),
        "size_offset": 0,
        "direction": "LTR",
        "HYPE_WORDS": ["INCREDIBILE!", "LEGGENDA!", "PAZZESCO!", "DIVINO!", "PERFETTO!"],
        "text": {
            "PLAY": "GIOCA",
            "SETTINGS": "IMPOSTAZIONI",
            "COLLECTION": "COLLEZIONE",
            "TRAINING": "TRAINING",
            "EXIT": "ESCI",
            "LAYER": "STRATO",
            "QUOTA": "QUOTA",
            "TRIBUTE": "TRIBUTO",
            "JUDGMENT": "GIUDIZIO",
            "LABOR": "LAVORO",
            "FAVOR": "FAVORE",
            "TOTAL": "TOTALE",
            "MENU": "MENU",
            "SHIFT_SCORE": "PUNTEGGIO",
            "DEMO_TITLE": "DEMO COMPLETATA",
            "DEMO_MSG": "Sei sopravvissuto a 8 strati... per ora.\nIl debito del Faraone non è pagato.",
            "ENTER_ETERNITY": "ETERNITA",
            "FREEDOM_1": "La liberta e un'altra prigione.",
            "FREEDOM_2": "Debito pagato. I blocchi restano.",
            "PHARAOH_1": "Lavora di piu.",
            "PHARAOH_2": "La pietra attende.",
            "PAUSE_MSG": "Torna al Menu?",
            "YES": "SI",
            "NO": "NO",
            "PAYMENT": "PAGAMENTO",
            "TOTAL_DEBT": "DEBITO TOTALE",
            "CONTINUE": "CONTINUA",
            "COLOR_MATCH": "COLORI!",
            "RUNE_CHIPS": "FRAMMENTI!",
            "GAMBLE_WIN": "VITTORIA!",
            "REROLL": "RILANCIA!",
            "RUNE_APPLIED": "RUNA USATA!",
            "ARCH_BONUS": "Bonus Architetto",
            "DEMO_HINT_MSG": "Paga il debito per il vero finale.",
            "RESET_BTN": "RESETTA",
            "BTN_TRY_AGAIN": "RIPROVA",
            "LBL_PYRO_BOSS": "BOSS PYRO",
            "PYRO_DEFEATED": "MODALITA PYRO SCONFITTA",
            "YOU_DIED": "SEI MORTO",
            "RESET_CONFIRM_TITLE": "CANCELLARE?",
            "RESET_CONFIRM_MSG": "Tutti i progressi verranno persi.\nSei sicuro?",
            # --- TUTORIAL (IT) ---
            "TUT_STEP0_TITLE": "BENVENUTO A SPHENKS",
            "TUT_STEP0_MSG": "Benvenuto, Architetto.\nIl Faraone esige una griglia perfetta.\nTrascina i blocchi per iniziare.",
            "TUT_STEP1_TITLE": "CONTROLLI MAESTRI",
            "TUT_STEP1_MSG": "La precisione è fondamentale.\nPremi 'R' per RUOTARE.\nPremi 'E' per CAPOVOLGERE.",
            "TUT_STEP2_TITLE": "PURIFICA LA MANO",
            "TUT_STEP2_MSG": "Alcuni blocchi sono difettosi.\nTrascina nel CESTINO ROSSO\nper scartare a un costo.",
            "TUT_STEP3_TITLE": "PUNTEGGIO E STRATEGIA",
            "TUT_STEP3_MSG": "Riempi le righe per fare punti.\nLe combo moltiplicano Lavoro e Favore.\nRaggiungi la Quota per sopravvivere.",
            "TUT_STEP4_TITLE": "IL TUO ARSENALE",
            "TUT_STEP4_MSG": "Non sei solo.\nRune e Oggetti appariranno qui.\nSono strumenti degli dei.",
            "TUT_STEP5_TITLE": "USA LA TUA RUNA",
            "TUT_STEP5_MSG": "È apparsa una Runa!\nTrascina la RUNA su un blocco in mano\nper incantarlo con potere.",
            "TUT_STEP6_TITLE": "SEI PRONTO!",
            "TUT_STEP6_MSG": "Le basi sono fatte.\nOra sopravvivi agli strati infiniti.\nIl Faraone ti osserva.",
            "BEST_RUN": "Migliore Prestazione",
            "ITEMS": {
                "sniper": {"name": "Tiratore", "desc": "Gli abbinamenti ai bordi danno x2 moltiplicatore."},
                "miner": {"name": "Minatore", "desc": "+$1 per ogni blocco di pietra rimosso."},
                "architect": {"name": "Architetto", "desc": "Piazzamenti senza rimozione +50 punti."},
                "void_walker": {"name": "Camminante del Vuoto", "desc": "x3 moltiplicatore quando vuoto < 5."},
                "midas": {"name": "Mida", "desc": "+$0,50 per ogni blocco rimosso."},
                "recycler": {"name": "Riciclatore", "desc": "I blocchi scartati diventano gratuiti."},
                "blood_pact": {"name": "Patto di Sangue", "desc": "x4 moltiplicatore, -1 capacità vuoto."},
                "savings_bond": {"name": "Obbligazione di Risparmio", "desc": "+20% interessi alla fine del turno."},
                "golden_ticket": {"name": "Biglietto d'Oro", "desc": "+$3 per ogni blocco d'oro posizionato."},
                "gamblers_dice": {"name": "Dadi del Giocatore", "desc": "25% distruggi blocco per x5 punti."},
                "ruby_lens": {"name": "Lente di Rubino", "desc": "+2 moltiplicatore per ogni blocco rosso."},
                "sapphire_lens": {"name": "Lente di Zaffiro", "desc": "+2 moltiplicatore per ogni blocco blu."},
                "dark_matter": {"name": "Materia Oscura", "desc": "Ottieni un enorme x10 moltiplicatore."},
                "infinity_stone": {"name": "Pietra dell'Infinito", "desc": "+$5 e x2 moltiplicatore al rimozione."},
                "chronos": {"name": "Chronos", "desc": "+50% interessi alla fine del turno."},
                "rune_fire": {"name": "Runa di Fuoco", "desc": "Distrugge area 3x3."},
                "rune_ice": {"name": "Runa di Ghiaccio", "desc": "Congela un blocco."},
                "rune_void": {"name": "Runa del Vuoto", "desc": "Distrugge stesso colore."},
                "rune_wind": {"name": "Runa del Vento", "desc": "Sposta riga orizzontalmente."},
                "rune_earth": {"name": "Runa della Terra", "desc": "Converti in blocco di pietra."},
                "refresh_shop": {"name": "Aggiorna", "desc": "Aggiorna il bazaar."},
                "unknown": {"name": "Sconosciuto", "desc": "Artefatto misterioso."}
            },
            "BAZAAR": "Bazaar",
            "TOTEMS": "Totems",
            "RUNES": "Rune",
            "NEXT_ROUND": "Prossimo >",
            "LBL_ROTATE": "RUOTARE",
            "LBL_FLIP": "CAPOVOLGERE",
            "BTN_COMING_SOON": "PRESTO",
            "COMING_SOON_TITLE": "IN ARRIVO v1.0",
            "CS_PYRO": "Nuova Modalità Pyro 🔥",
            "CS_LANGS": "Supporto Russo e Arabo 🌍",
            "CS_STORY": "Storia Completa: 4 Mondi 📜",
            "CS_VISUALS": "Nuovi VFX e Sfondi ✨",
            "CS_MORE": "E molto altro! 🚀",
            "BACK": "INDIETRO"
        }
    }
}