# languages.py

LANGUAGES = {
    "EN": {
        "name": "ENGLISH",
        "font": "assets/fonts/Alagard.ttf",
        "size_offset": 0,
        "direction": "LTR",
        "HYPE_WORDS": ["AMAZING!", "LEGEND!", "INSANE!", "GODLIKE!", "PERFECT!"],
        "text": {
            "PLAY": "PLAY",
            "SETTINGS": "SETTINGS",
            "COLLECTION": "COLLECTION",
            "TRAINING": "TRAINING",
            "EXIT": "EXIT",
            "LAYER": "LAYER",
            "QUOTA": "QUOTA",
            "TRIBUTE": "TRIBUTE",
            "JUDGMENT": "JUDGMENT",
            "LABOR": "LABOR",
            "FAVOR": "FAVOR",
            "TOTAL": "TOTAL",
            "MENU": "MENU",
            "SHIFT_SCORE": "SHIFT SCORE",
            "DEMO_TITLE": "DEMO COMPLETED",
            "DEMO_MSG": "You have survived 8 Layers... for now.\nThe Pharaoh's debt is not fully paid.",
            "ENTER_ETERNITY": "ENTER ETERNITY",
            "FREEDOM_1": "Freedom is just another prison.",
            "FREEDOM_2": "The debt is paid. The blocks remain.",
            "PHARAOH_1": "Work harder.",
            "PHARAOH_2": "The stone waits.",
            "PAUSE_MSG": "Return to Main Menu?",
            "YES": "YES",
            "NO": "NO",
            "PAYMENT": "PAYMENT",
            "TOTAL_DEBT": "TOTAL DEBT",
            "CONTINUE": "CONTINUE",
            "COLOR_MATCH": "COLOR MATCH!",
            "RUNE_CHIPS": "RUNE CHIPS!",
            "GAMBLE_WIN": "GAMBLE WIN!",
            "REROLL": "REROLL!",
            "RUNE_APPLIED": "RUNE APPLIED!",
            "ARCH_BONUS": "Architect Bonus",
            "TUT_STEP0_TITLE": "WELCOME TO SPHENKS",
            "TUT_STEP0_MSG": "Welcome, Architect.\nThe Pharaoh demands a perfect grid.\nDrag blocks to the board to begin.",
            "TUT_STEP1_TITLE": "MASTER CONTROLS",
            "TUT_STEP1_MSG": "Precision is key.\nPress 'R' to ROTATE blocks.\nPress 'E' to FLIP blocks.",
            "TUT_STEP2_TITLE": "PURIFY THE HAND",
            "TUT_STEP2_MSG": "Some blocks are flawed.\nDrag a block to the RED TRASH ICON\nto discard it for a small cost.",
            "TUT_STEP3_TITLE": "SCORING & STRATEGY",
            "TUT_STEP3_MSG": "Fill rows completely to score.\nCombos multiply your Labor and Favor.\nReach the Quota to survive.",
            "TUT_STEP4_TITLE": "MEET YOUR ARSENAL",
            "TUT_STEP4_MSG": "You are not alone.\nRunes and Items will appear here.\nThey are tools of the gods.",
            "TUT_STEP5_TITLE": "USE YOUR RUNE",
            "TUT_STEP5_MSG": "A Rune has appeared!\nDrag the RUNE onto a block in your hand\nto enchant it with power.",
            "TUT_STEP6_TITLE": "YOU'RE READY!",
            "TUT_STEP6_MSG": "The basics are done.\nNow, survive the infinite layers.\nThe Pharaoh is watching.",
        }
    },
    "TR": {
        "name": "TURKCE",
        "font": "assets/fonts/Alagard.ttf",
        "size_offset": 0,
        "direction": "LTR",
        "HYPE_WORDS": ["EFSANE!", "HARIKA!", "INANILMAZ!", "SOV YAPTIN!", "MUKEMMEL!"],
        "text": {
            "PLAY": "OYNA",
            "SETTINGS": "AYARLAR",
            "COLLECTION": "KOLEKSIYON",
            "TRAINING": "EGITIM",
            "EXIT": "CIKIS",
            "LAYER": "KATMAN",
            "QUOTA": "KOTA",
            "TRIBUTE": "HARAC",
            "JUDGMENT": "YARGI",
            "LABOR": "EMEK",
            "FAVOR": "LUTUF",
            "TOTAL": "TOPLAM",
            "MENU": "MENU",
            "SHIFT_SCORE": "VARDIYA SKORU",
            "DEMO_TITLE": "DEMO TAMAMLANDI",
            "DEMO_MSG": "8 Katmani hayatta kalarak bitirdin...\nFiravun'a olan borcun henuz bitmedi.",
            "ENTER_ETERNITY": "SONSUZLUK MODU",
            "FREEDOM_1": "Ozgurluk baska bir hapishanedir.",
            "FREEDOM_2": "Borc bitti. Bloklar bitmedi.",
            "PHARAOH_1": "Daha siki calis.",
            "PHARAOH_2": "Taslar seni bekler.",
            "PAUSE_MSG": "Ana Menuye Don?",
            "YES": "EVET",
            "NO": "HAYIR",
            "PAYMENT": "ODEME",
            "TOTAL_DEBT": "KALAN BORC",
            "CONTINUE": "DEVAM ET",
            "COLOR_MATCH": "RENK UYUMU!",
            "RUNE_CHIPS": "RUN PARCALARI!",
            "GAMBLE_WIN": "KUMAR KAZANDI!",
            "REROLL": "YENILE!",
            "RUNE_APPLIED": "RUN BASILDI!",
            "ARCH_BONUS": "Mimar Bonusu",
            "TUT_STEP0_TITLE": "SPHENKS'E HOSGELDIN",
            "TUT_STEP0_MSG": "Hosgeldin Mimar.\nFiravun kusursuz bir yapi ister.\nBaslamak icin blogu izgaraya surukle.",
            "TUT_STEP1_TITLE": "KONTROL USTALIGI",
            "TUT_STEP1_MSG": "Hassasiyet onemlidir.\n'R' ile DONDUR.\n'E' ile TERS CEVIR.",
            "TUT_STEP2_TITLE": "ELI ARINDIR",
            "TUT_STEP2_MSG": "Bazi bloklar kusurludur.\nOnlari yok etmek icin KIRMIZI COP KUTUSUNA\nsurukle. Bunun bir bedeli vardir.",
            "TUT_STEP3_TITLE": "SKOR VE STRATEJI",
            "TUT_STEP3_MSG": "Satirlari doldurarak puan kazan.\nKombolar Emek ve Lutuf puanini katlar.\nHayatta kalmak icin Kotaya ulas.",
            "TUT_STEP4_TITLE": "CEPHANELIK",
            "TUT_STEP4_MSG": "Yalniz degilsin.\nRunler ve Esyalar burada belirir.\nOnlar tanrilarin araclaridir.",
            "TUT_STEP5_TITLE": "RUNU KULLAN",
            "TUT_STEP5_MSG": "Bir Run belirdi!\nRunu elindeki bir blogun uzerine surukle\nve onu gucle donat.",
            "TUT_STEP6_TITLE": "HAZIRSIN!",
            "TUT_STEP6_MSG": "Temelleri ogrendin.\nSimdi sonsuz katmanlarda hayatta kal.\nFiravun seni izliyor.",
        }
    },
    "DE": {
        "name": "DEUTSCH",
        "font": "assets/fonts/Alagard.ttf",
        "size_offset": 0,
        "direction": "LTR",
        "HYPE_WORDS": ["WUNDERBAR!", "LEGENDE!", "WAHNSINN!", "PERFEKT!", "MEISTER!"],
        "text": {
            "PLAY": "SPIELEN",
            "SETTINGS": "EINSTELLUNG",
            "COLLECTION": "SAMMLUNG",
            "TRAINING": "TRAINING",
            "EXIT": "BEENDEN",
            "LAYER": "EBENE",
            "QUOTA": "QUOTE",
            "TRIBUTE": "TRIBUT",
            "JUDGMENT": "URTEIL",
            "LABOR": "ARBEIT",
            "FAVOR": "GUNST",
            "TOTAL": "GESAMT",
            "MENU": "MENU",
            "SHIFT_SCORE": "SCHICHT PUNKTE",
            "DEMO_TITLE": "DEMO BEENDET",
            "DEMO_MSG": "Du hast 8 Ebenen überlebt... für jetzt.\nDie Schuld des Pharaos ist noch nicht beglichen.",
            "ENTER_ETERNITY": "EWIGKEIT",
            "FREEDOM_1": "Freiheit ist nur ein weiteres Gefängnis.",
            "FREEDOM_2": "Schuld beglichen. Blöcke bleiben.",
            "PHARAOH_1": "Arbeite härter.",
            "PHARAOH_2": "Der Stein wartet.",
            "PAUSE_MSG": "Zurück zum Menü?",
            "YES": "JA",
            "NO": "NEIN",
            "PAYMENT": "ZAHLUNG",
            "TOTAL_DEBT": "RESTSCHULD",
            "CONTINUE": "WEITER",
            "COLOR_MATCH": "FARB-COMBO!",
            "RUNE_CHIPS": "RUNEN SPLITTER!",
            "GAMBLE_WIN": "GEWINN!",
            "REROLL": "NEU WÜRFELN!",
            "RUNE_APPLIED": "RUNE BENUTZT!",
            "ARCH_BONUS": "Architekten Bonus",
            # --- TUTORIAL (DE) ---
            "TUT_STEP0_TITLE": "WILLKOMMEN BEI SPHENKS",
            "TUT_STEP0_MSG": "Willkommen, Architekt.\nDer Pharao verlangt ein perfektes Raster.\nZiehe Blöcke auf das Brett, um zu beginnen.",
            "TUT_STEP1_TITLE": "STEUERUNG MEISTERN",
            "TUT_STEP1_MSG": "Präzision ist der Schlüssel.\nDrücke 'R' zum DREHEN.\nDrücke 'E' zum WENDEN.",
            "TUT_STEP2_TITLE": "HAND REINIGEN",
            "TUT_STEP2_MSG": "Manche Blöcke sind fehlerhaft.\nZiehe sie in den ROTEN MÜLLEIMER,\num sie gegen eine Gebühr zu entsorgen.",
            "TUT_STEP3_TITLE": "PUNKTE & STRATEGIE",
            "TUT_STEP3_MSG": "Fülle Reihen komplett für Punkte.\nKombos vervielfachen Arbeit und Gunst.\nErreiche die Quote zum Überleben.",
            "TUT_STEP4_TITLE": "DEIN ARSENAL",
            "TUT_STEP4_MSG": "Du bist nicht allein.\nRunen und Items erscheinen hier.\nSie sind Werkzeuge der Götter.",
            "TUT_STEP5_TITLE": "BENUTZE DEINE RUNE",
            "TUT_STEP5_MSG": "Eine Rune ist erschienen!\nZiehe die RUNE auf einen Block in deiner Hand,\num ihn mit Macht zu verzaubern.",
            "TUT_STEP6_TITLE": "DU BIST BEREIT!",
            "TUT_STEP6_MSG": "Die Grundlagen sind gelegt.\nÜberlebe nun die unendlichen Ebenen.\nDer Pharao beobachtet dich."
        }
    },
    "ES": {
        "name": "ESPANOL",
        "font": "assets/fonts/Alagard.ttf",
        "size_offset": 0,
        "direction": "LTR",
        "HYPE_WORDS": ["INCREIBLE!", "LEYENDA!", "LOCO!", "PERFECTO!", "MAESTRO!"],
        "text": {
            "PLAY": "JUGAR",
            "SETTINGS": "AJUSTES",
            "COLLECTION": "COLECCION",
            "TRAINING": "ENTRENAR",
            "EXIT": "SALIR",
            "LAYER": "CAPA",
            "QUOTA": "CUOTA",
            "TRIBUTE": "TRIBUTO",
            "JUDGMENT": "JUICIO",
            "LABOR": "LABOR",
            "FAVOR": "FAVOR",
            "TOTAL": "TOTAL",
            "MENU": "MENU",
            "SHIFT_SCORE": "PUNTOS TURNO",
            "DEMO_TITLE": "DEMO COMPLETADA",
            "DEMO_MSG": "Has sobrevivido 8 Capas... por ahora.\nLa deuda del Faraón no está pagada.",
            "ENTER_ETERNITY": "ETERNIDAD",
            "FREEDOM_1": "La libertad es otra prisión.",
            "FREEDOM_2": "Deuda pagada. Los bloques quedan.",
            "PHARAOH_1": "Trabaja más.",
            "PHARAOH_2": "La piedra espera.",
            "PAUSE_MSG": "Volver al Menú?",
            "YES": "SI",
            "NO": "NO",
            "PAYMENT": "PAGO",
            "TOTAL_DEBT": "DEUDA TOTAL",
            "CONTINUE": "CONTINUAR",
            "COLOR_MATCH": "COLOR COMBO!",
            "RUNE_CHIPS": "FICHAS RUNA!",
            "GAMBLE_WIN": "GANASTE!",
            "REROLL": "RE-TIRAR!",
            "RUNE_APPLIED": "RUNA APLICADA!",
            "ARCH_BONUS": "Bono Arquitecto",
            # --- TUTORIAL (ES) ---
            "TUT_STEP0_TITLE": "BIENVENIDO A SPHENKS",
            "TUT_STEP0_MSG": "Bienvenido, Arquitecto.\nEl Faraón exige una cuadrícula perfecta.\nArrastra bloques al tablero para comenzar.",
            "TUT_STEP1_TITLE": "CONTROLES MAESTROS",
            "TUT_STEP1_MSG": "La precisión es clave.\nPresiona 'R' para ROTAR.\nPresiona 'E' para VOLTEAR.",
            "TUT_STEP2_TITLE": "PURIFICA LA MANO",
            "TUT_STEP2_MSG": "Algunos bloques son defectuosos.\nArrastra al BASURERO ROJO\npara descartar por un costo.",
            "TUT_STEP3_TITLE": "PUNTUACIÓN Y ESTRATEGIA",
            "TUT_STEP3_MSG": "Llena filas para ganar puntos.\nLos combos multiplican Labor y Favor.\nAlcanza la Cuota para sobrevivir.",
            "TUT_STEP4_TITLE": "TU ARSENAL",
            "TUT_STEP4_MSG": "No estás solo.\nRunas y Objetos aparecerán aquí.\nSon herramientas de los dioses.",
            "TUT_STEP5_TITLE": "USA TU RUNA",
            "TUT_STEP5_MSG": "¡Apareció una Runa!\nArrastra la RUNA a un bloque en tu mano\npara encantarlo con poder.",
            "TUT_STEP6_TITLE": "¡ESTÁS LISTO!",
            "TUT_STEP6_MSG": "Lo básico está hecho.\nAhora sobrevive a las capas infinitas.\nEl Faraón te observa."
        }
    },
    
    "ZH": {
        "name": "CHINESE",
        "font": "assets/fonts/Zpix.ttf",
        "size_offset": 2,
        "direction": "LTR",
        "HYPE_WORDS": ["太棒了!", "传说!", "疯狂!", "超神!", "完美!"],
        "text": {
            "PLAY": "开始游戏",
            "SETTINGS": "设置",
            "COLLECTION": "收藏",
            "TRAINING": "教程",
            "EXIT": "退出",
            "LAYER": "层",
            "QUOTA": "配额",
            "TRIBUTE": "贡品",
            "JUDGMENT": "审判",
            "LABOR": "劳力",
            "FAVOR": "恩赐",
            "TOTAL": "总分",
            "MENU": "菜单",
            "SHIFT_SCORE": "班次得分",
            "DEMO_TITLE": "演示结束",
            "DEMO_MSG": "你幸存了8层... 暂时。\n法老的债务尚未还清。",
            "ENTER_ETERNITY": "进入永恒",
            "FREEDOM_1": "自由只是另一种牢笼。",
            "FREEDOM_2": "债务已清。方块仍在。",
            "PHARAOH_1": "更努力工作。",
            "PHARAOH_2": "石头在等待。",
            "PAUSE_MSG": "返回主菜单？",
            "YES": "是",
            "NO": "否",
            "PAYMENT": "支付",
            "TOTAL_DEBT": "总债务",
            "CONTINUE": "继续",
            "COLOR_MATCH": "颜色匹配!",
            "RUNE_CHIPS": "符文碎片!",
            "GAMBLE_WIN": "赌博获胜!",
            "REROLL": "重掷!",
            "RUNE_APPLIED": "符文已应用!",
            "ARCH_BONUS": "建筑师奖励",
            # --- TUTORIAL (ZH) ---
            "TUT_STEP0_TITLE": "欢迎来到 SPHENKS",
            "TUT_STEP0_MSG": "欢迎你，建筑师。\n法老要求完美的网格。\n将方块拖到棋盘上开始。",
            "TUT_STEP1_TITLE": "掌握控制",
            "TUT_STEP1_MSG": "精准是关键。\n按 'R' 旋转方块。\n按 'E' 翻转方块。",
            "TUT_STEP2_TITLE": "净化手牌",
            "TUT_STEP2_MSG": "有些方块有缺陷。\n拖到红色垃圾桶\n花费金币丢弃它们。",
            "TUT_STEP3_TITLE": "得分与策略",
            "TUT_STEP3_MSG": "填满行以得分。\n连击倍增劳力和恩赐。\n达到配额以生存。",
            "TUT_STEP4_TITLE": "你的军火库",
            "TUT_STEP4_MSG": "你并不孤单。\n符文和道具会出现在这里。\n它们是神的工具。",
            "TUT_STEP5_TITLE": "使用符文",
            "TUT_STEP5_MSG": "符文出现了！\n将符文拖到手牌中的方块上\n赋予它力量。",
            "TUT_STEP6_TITLE": "准备好了！",
            "TUT_STEP6_MSG": "基础已完成。\n现在在无限层中生存。\n法老在注视着你。"
        }
    },
    "PT": {
        "name": "PORTUGUES",
        "font": "assets/fonts/Alagard.ttf",
        "size_offset": 0,
        "direction": "LTR",
        "HYPE_WORDS": ["INCRIVEL!", "LENDA!", "INSANO!", "DIVINO!", "PERFEITO!"],
        "text": {
            "PLAY": "JOGAR",
            "SETTINGS": "CONFIGURACAO",
            "COLLECTION": "COLECAO",
            "TRAINING": "TREINO",
            "EXIT": "SAIR",
            "LAYER": "CAMADA",
            "QUOTA": "META",
            "TRIBUTE": "TRIBUTO",
            "JUDGMENT": "JULGAMENTO",
            "LABOR": "TRABALHO",
            "FAVOR": "FAVOR",
            "TOTAL": "TOTAL",
            "MENU": "MENU",
            "SHIFT_SCORE": "PONTOS TURNO",
            "DEMO_TITLE": "DEMO CONCLUIDA",
            "DEMO_MSG": "Voce sobreviveu 8 Camadas... por enquanto.\nA divida do Farao nao foi paga.",
            "ENTER_ETERNITY": "ETERNIDADE",
            "FREEDOM_1": "Liberdade e outra prisao.",
            "FREEDOM_2": "Divida paga. Os blocos ficam.",
            "PHARAOH_1": "Trabalhe mais.",
            "PHARAOH_2": "A pedra espera.",
            "PAUSE_MSG": "Voltar ao Menu?",
            "YES": "SIM",
            "NO": "NAO",
            "PAYMENT": "PAGAMENTO",
            "TOTAL_DEBT": "DIVIDA TOTAL",
            "CONTINUE": "CONTINUAR",
            "COLOR_MATCH": "COR COMBINADA!",
            "RUNE_CHIPS": "FRAGMENTOS!",
            "GAMBLE_WIN": "VITORIA!",
            "REROLL": "ROLAR!",
            "RUNE_APPLIED": "RUNA APLICADA!",
            "ARCH_BONUS": "Bonus Arquiteto",
            # --- TUTORIAL (PT) ---
            "TUT_STEP0_TITLE": "BEM-VINDO AO SPHENKS",
            "TUT_STEP0_MSG": "Bem-vindo, Arquiteto.\nO Faraó exige uma grade perfeita.\nArraste blocos para o tabuleiro para começar.",
            "TUT_STEP1_TITLE": "CONTROLES MESTRES",
            "TUT_STEP1_MSG": "Precisão é a chave.\nPressione 'R' para GIRAR.\nPressione 'E' para VIRAR.",
            "TUT_STEP2_TITLE": "PURIFIQUE A MÃO",
            "TUT_STEP2_MSG": "Alguns blocos são falhos.\nArraste para a LIXEIRA VERMELHA\npara descartar por um custo.",
            "TUT_STEP3_TITLE": "PONTUAÇÃO E ESTRATÉGIA",
            "TUT_STEP3_MSG": "Preencha linhas para pontuar.\nCombos multiplicam Trabalho e Favor.\nAtinga a Meta para sobreviver.",
            "TUT_STEP4_TITLE": "SEU ARSENAL",
            "TUT_STEP4_MSG": "Você não está sozinho.\nRunas e Itens aparecerão aqui.\nSão ferramentas dos deuses.",
            "TUT_STEP5_TITLE": "USE SUA RUNA",
            "TUT_STEP5_MSG": "Uma Runa apareceu!\nArraste a RUNA para um bloco na sua mão\npara encantá-lo com poder.",
            "TUT_STEP6_TITLE": "VOCÊ ESTÁ PRONTO!",
            "TUT_STEP6_MSG": "O básico está feito.\nAgora sobreviva às camadas infinitas.\nO Faraó está observando."
        }
    },
    "FR": {
        "name": "FRANCAIS",
        "font": "assets/fonts/Alagard.ttf",
        "size_offset": 0,
        "direction": "LTR",
        "HYPE_WORDS": ["INCROYABLE!", "LEGENDE!", "DEMENT!", "DIVIN!", "PARFAIT!"],
        "text": {
            "PLAY": "JOUER",
            "SETTINGS": "PARAMETRES",
            "COLLECTION": "COLLECTION",
            "TRAINING": "TUTORIEL",
            "EXIT": "QUITTER",
            "LAYER": "COUCHE",
            "QUOTA": "QUOTA",
            "TRIBUTE": "TRIBUT",
            "JUDGMENT": "JUGEMENT",
            "LABOR": "LABEUR",
            "FAVOR": "FAVEUR",
            "TOTAL": "TOTAL",
            "MENU": "MENU",
            "SHIFT_SCORE": "SCORE TOUR",
            "DEMO_TITLE": "DEMO TERMINEE",
            "DEMO_MSG": "Vous avez survécu à 8 couches... pour l'instant.\nLa dette du Pharaon n'est pas payée.",
            "ENTER_ETERNITY": "ETERNITE",
            "FREEDOM_1": "La liberte est une autre prison.",
            "FREEDOM_2": "Dette payee. Les blocs restent.",
            "PHARAOH_1": "Travaillez plus dur.",
            "PHARAOH_2": "La pierre attend.",
            "PAUSE_MSG": "Retour au Menu?",
            "YES": "OUI",
            "NO": "NON",
            "PAYMENT": "PAIEMENT",
            "TOTAL_DEBT": "DETTE TOTALE",
            "CONTINUE": "CONTINUER",
            "COLOR_MATCH": "COULEURS!",
            "RUNE_CHIPS": "FRAGMENTS!",
            "GAMBLE_WIN": "VICTOIRE!",
            "REROLL": "RELANCER!",
            "RUNE_APPLIED": "RUNE APPLIQUEE!",
            "ARCH_BONUS": "Bonus Architecte",
            # --- TUTORIAL (FR) ---
            "TUT_STEP0_TITLE": "BIENVENUE À SPHENKS",
            "TUT_STEP0_MSG": "Bienvenue, Architecte.\nLe Pharaon exige une grille parfaite.\nGlissez des blocs sur le plateau pour commencer.",
            "TUT_STEP1_TITLE": "MAÎTRISEZ LES COMMANDES",
            "TUT_STEP1_MSG": "La précision est la clé.\nAppuyez sur 'R' pour PIVOTER.\nAppuyez sur 'E' pour RETOURNER.",
            "TUT_STEP2_TITLE": "PURIFIEZ LA MAIN",
            "TUT_STEP2_MSG": "Certains blocs sont imparfaits.\nGlissez vers la POUBELLE ROUGE\npour jeter contre un coût.",
            "TUT_STEP3_TITLE": "SCORE ET STRATÉGIE",
            "TUT_STEP3_MSG": "Remplissez les lignes pour marquer.\nLes combos multiplient Labeur et Faveur.\nAtteignez le Quota pour survivre.",
            "TUT_STEP4_TITLE": "VOTRE ARSENAL",
            "TUT_STEP4_MSG": "Vous n'êtes pas seul.\nRunes et Objets apparaîtront ici.\nCe sont des outils des dieux.",
            "TUT_STEP5_TITLE": "UTILISEZ VOTRE RUNE",
            "TUT_STEP5_MSG": "Une Rune est apparue !\nGlissez la RUNE sur un bloc en main\npour l'enchanter.",
            "TUT_STEP6_TITLE": "VOUS ÊTES PRÊT !",
            "TUT_STEP6_MSG": "Les bases sont acquises.\nSurvivez aux couches infinies.\nLe Pharaon vous observe."
        }
    },
    "IT": {
        "name": "ITALIANO",
        "font": "assets/fonts/Alagard.ttf",
        "size_offset": 0,
        "direction": "LTR",
        "HYPE_WORDS": ["INCREDIBILE!", "LEGGENDA!", "PAZZESCO!", "DIVINO!", "PERFETTO!"],
        "text": {
            "PLAY": "GIOCA",
            "SETTINGS": "IMPOSTAZIONI",
            "COLLECTION": "COLLEZIONE",
            "TRAINING": "TRAINING",
            "EXIT": "ESCI",
            "LAYER": "STRATO",
            "QUOTA": "QUOTA",
            "TRIBUTE": "TRIBUTO",
            "JUDGMENT": "GIUDIZIO",
            "LABOR": "LAVORO",
            "FAVOR": "FAVORE",
            "TOTAL": "TOTALE",
            "MENU": "MENU",
            "SHIFT_SCORE": "PUNTEGGIO",
            "DEMO_TITLE": "DEMO COMPLETATA",
            "DEMO_MSG": "Sei sopravvissuto a 8 strati... per ora.\nIl debito del Faraone non è pagato.",
            "ENTER_ETERNITY": "ETERNITA",
            "FREEDOM_1": "La liberta e un'altra prigione.",
            "FREEDOM_2": "Debito pagato. I blocchi restano.",
            "PHARAOH_1": "Lavora di piu.",
            "PHARAOH_2": "La pietra attende.",
            "PAUSE_MSG": "Torna al Menu?",
            "YES": "SI",
            "NO": "NO",
            "PAYMENT": "PAGAMENTO",
            "TOTAL_DEBT": "DEBITO TOTALE",
            "CONTINUE": "CONTINUA",
            "COLOR_MATCH": "COLORI!",
            "RUNE_CHIPS": "FRAMMENTI!",
            "GAMBLE_WIN": "VITTORIA!",
            "REROLL": "RILANCIA!",
            "RUNE_APPLIED": "RUNA USATA!",
            "ARCH_BONUS": "Bonus Architetto",
            # --- TUTORIAL (IT) ---
            "TUT_STEP0_TITLE": "BENVENUTO A SPHENKS",
            "TUT_STEP0_MSG": "Benvenuto, Architetto.\nIl Faraone esige una griglia perfetta.\nTrascina i blocchi per iniziare.",
            "TUT_STEP1_TITLE": "CONTROLLI MAESTRI",
            "TUT_STEP1_MSG": "La precisione è fondamentale.\nPremi 'R' per RUOTARE.\nPremi 'E' per CAPOVOLGERE.",
            "TUT_STEP2_TITLE": "PURIFICA LA MANO",
            "TUT_STEP2_MSG": "Alcuni blocchi sono difettosi.\nTrascina nel CESTINO ROSSO\nper scartare a un costo.",
            "TUT_STEP3_TITLE": "PUNTEGGIO E STRATEGIA",
            "TUT_STEP3_MSG": "Riempi le righe per fare punti.\nLe combo moltiplicano Lavoro e Favore.\nRaggiungi la Quota per sopravvivere.",
            "TUT_STEP4_TITLE": "IL TUO ARSENALE",
            "TUT_STEP4_MSG": "Non sei solo.\nRune e Oggetti appariranno qui.\nSono strumenti degli dei.",
            "TUT_STEP5_TITLE": "USA LA TUA RUNA",
            "TUT_STEP5_MSG": "È apparsa una Runa!\nTrascina la RUNA su un blocco in mano\nper incantarlo con potere.",
            "TUT_STEP6_TITLE": "SEI PRONTO!",
            "TUT_STEP6_MSG": "Le basi sono fatte.\nOra sopravvivi agli strati infiniti.\nIl Faraone ti osserva."
        }
    }
}